### ISSUE TITLE
Éttermi integráció

### ISSUE THREAD

**Issue by Hsxsky** [rkeeperhun/Endpoint_Doc#1]
Van nálunk online bankkártyás fizetési lehetőség:
pay_type - type of payment: 0 - cash to the courier, 1 - by bank card to the courier (required)
Mit írjak ilyenkor a „pay_type” mezőbe.
 
Lehet nálunk kéni extra feltétet a pizzára.
 
Ehhez tud küldeni egy példa kódot?
 
Ahogy nézem árak nincsenek az átadott adatok között.
Lehet valahogy felülbírálni egy árat webes akció miatt?
 
Szeretnénk a Netpincért is használni. 
Ez kapcsolat mellett működhet a netpincér is?

**Comment by avatarf** [comment]
Üdv, 
ELnézést a kései válaszért, de ez az üzenet valahogy átcsúszott a réseken. Megpróbálok minden kérdésre válaszolni ebben az üzenetben, de egyesekhez majd pontositom a documentációt is.


1️⃣   _Van nálunk online bankkártyás fizetési lehetőség: ..._
Az online fizetés tényének átadásához a `pay_online_type`-t kell használni. Ez ahogy látom nem volt egyértelműen leírva a documentációban, frissíteni fogjuk.

De a lényeg hogy a rendelés feladásánal a `pay_online_type`-nek `1`-es értéket kell adni. És nem elég csak a rendelést POST-olni, hanem mituán a rendelés fel lett adva, és a válaszból már látszik a `visit_id` akkor még egy POST requestet kell küldeni amiben szerepel a `visit_id` is. A documentáció ezen paragrafusában ez le van már írva -- https://github.com/rkeeperhun/Endpoint_Doc/blob/master/vendor_api_doc.md#post-order-payed

* a `pay_type` elem arra használható hogy abban az esteben ha a szállítónak fizet az ügyfél akkor ki lehessen választani előre hogy kártyával akar-e fizetni vagy nem.

2️⃣   _Lehet nálunk kéni extra feltétet a pizzára._
Igen lehet. Itt "modifier"-ekkel kell kiegészíteni a rendelés adatait. Itt s ahogy a termékek esetén ID-k alapján folyik a communikáció az önön és az endpoint rendszerén keresztül. Fontos hogy ezek az ID-k mindig synkrobna legyenek.

Példa rendelés

```
{
    "objectid": "109150003",
    "delivery_time": "2020-11-26T23:26:01",
    "comment": "lacitest",
    "order_type": 0,
    "pay_type": 0,
    "pay_online_type": 0,
    "client": {
        "phone": "+36303857256",
        "email": "asdghfasd@djasd.hu",
        "ln": "Laci",
        "fn": "Farkas"
    },
    "order": [
        {
            "id": "1002217",
            "qnt": 5000,
            "type": "d",
            "items": [
                {
                  "id": 1000388,
                  "type": "m",
                  "qnt": 3000,
                  "items": []
                },
                {
                  "id": 1000488,
                  "type": "m",
                  "qnt": 1000,
                  "items": []
                }
            ]
        },
        {
            "id": "1001552",
            "qnt": 1000,
            "type": "d",
            "items": []
        }
    ]
}
```

Példa termék egy rendelésból, modifier-ek nélkül: 
`type:"d"` ◀️ "d" = dish
```
        {
            "id": "1001552",
            "qnt": 1000,
            "type": "d",
            "items": []
        }
```

Példa termék egy rendelésból, modifier-ekel: 
`type:"d"` ◀️ "d" = dish
`type:"m"` ◀️ "m" = modifier
```
        {
            "id": "1002217",
            "qnt": 5000,
            "type": "d",
            "items": [
                {
                  "id": 1000388,
                  "type": "m",
                  "qnt": 3000,
                  "items": []
                },
                {
                  "id": 1000488,
                  "type": "m",
                  "qnt": 1000,
                  "items": []
                }
            ]
        }
```
☝️  itt két modifer elemet adtuk az ételhez. Az egyikből egy darabot (pl.: a köret legyen hasáb), a másikból pedig 3-at (pl.: extra ketchup)

3️⃣   _Ahogy nézem árak nincsenek az átadott adatok között. Lehet valahogy felülbírálni egy árat webes akció miatt?_
Nem, sajnos nem lehetséges árat átadni. Az endpoint renszer nagyon szoros integrécióban működik a terminál rendzserével és bármi ami problémát jelentene ebben a szinkronban az nem lehetséges.

Elvileg lehetséges olyan modifier-t csinálni ami negatív értékkel bír, de ezt már inkább @rkeeperhun tudja megválaszolni.

4️⃣   _Szeretnénk a Netpincért is használni. Ez kapcsolat mellett működhet a netpincér is?_
Igen ez lehetséges. A netpincér renszerét már integráltuk az endpointba és nem jelent gondott ha a netpincéres és a saját integráció egymás mellett müködik. A netpincéres integráció elindításához is majd @rkeeperhun útmutatása szükséges.

**Comment by Hsxsky** [comment]
Ahogy nézem árak nincsenek az átadott adatok között. Lehet valahogy felülbírálni egy árat webes akció miatt?
Nem, sajnos nem lehetséges árat átadni. Az endpoint renszer nagyon szoros integrécióban működik a terminál rendzserével és bármi ami problémát jelentene ebben a szinkronban az nem lehetséges.

Van felület hol le lehet kérdezni az árakat?

**Comment by rkeeperhun** [comment]
Üdv,
Az árakat az RK7 Manager programból tudják megnézni, illetve az egyes termékekhez tartozó "id"-kat is innen lehet megnézni.

Jelenleg kedvezményeket még nem kezel a rendszerünk.

**Comment by Hsxsky** [comment]
Félreértett.
Az lenne a cél, hogy ne kelljen duplán rögzíteni az árváltozásokat.
Kézi másoláskor egész nagy a valószínűsége a hibának.
Rendelés kiszállításokat nagyon kellemetlen tud lenni, ha más van a számlán, mint amit a megrendelésbe látott.
Ezt el szeretném kerülni.

**Comment by handras78** [comment]
Kipróbáltam a rendelés leadást, de 404 -es hibát kapok mindig.
A hiba:

{"code":"rest_no_route","message":"No route was found matching the URL and request method.","data":{"status":404}}

Kaptunk restaurant id-t, logint és jelszót is. A hozzáférésünk nem jó még?

Így próbálom:

      $Url="https://endpoint.ucs.hu/wp-json/vendor/v1/postorder/".RKEEP_REST_ID;
      
      $Atad='{
    "objectid": "".RKEEP_REST_ID."",
    "delivery_time": "2021-07-20T12:26:01",
    "comment": "lacitest",
    "order_type": 0,
    "pay_type": 0,
    "pay_online_type": 0,
    "client": {
        "phone": "+36303857256",
        "email": "asdghfasjasd.hu",
        "ln": "Laci",
        "fn": "Farkas"
    },
    "order": [
        {
            "id": "1002217",
            "qnt": 5000,
            "type": "d",
            "items": []
        },
        {
            "id": "1001552",
            "qnt": 1000,
            "type": "d",
            "items": []
        }
    ]
}';

**Comment by avatarf** [comment]
👋  @handras78 
Úgy látom hogy `GET` requestként érkezett meg a request. Nézd meg kérlek hogy POST-ként külditek illetve hogy mindenképpen HTTPS-en menjen a communikáció.

Ha a credential-ökkel és vagy a rest IDval lenne a probléma akkor a hiba üzeneteben benne lenne hogy ezen a téren van probléma.

**Comment by handras78** [comment]
Köszönöm, ez lehetett a probléma.  Viszont most ilyen választ kapok:
Your access to this site has been limited by the site owner
Your access to this service has been limited. (HTTP response code 503)

A próbálkozások miatt letilthatott a másik oldal. 

![kép](https://user-images.githubusercontent.com/87700728/126329496-2c3dc8f2-9aec-4a83-84d4-08ae05d46bb3.png)

**Comment by avatarf** [comment]
@handras78 
Oh igen, ezen a szerveren elég érzékenyre van álltiva a firewall! Kivettem a blokkolást.
Ahogy az errorban is benne volt, user-agent nélkül vagy üres user-agent-el lett elküldve a request.

Mindjárt updatelem a documentációt hogy ezeket is kiemeljem.
De addig is kérlek tegyél be egy bármilyen user-agent-et a requestbe "xyz-restaurant-bot" és egy referer-re is szükség lesz, itt ajánlanám a az étterem/kávézó weboldalt megjelölni.

**Comment by handras78** [comment]
Lehet hogy először nem jól tettem be és úgy hívtam, de megint ugyanazt kapom.  Lehet hogy letiltott egyből a szerver? 

Így próbálkozok most, szerintem így jónak kell lennie. (először még nem így hívtam) 

      $ch = curl_init();
      
      $Url="https://endpoint.ucs.hu/wp-json/vendor/v1/postorder/".RKEEP_REST_ID;
      
      $Atad='{
    "objectid": "'.RKEEP_REST_ID.'",
    "delivery_time": "2021-07-20T12:26:01",
    "comment": "lacitest",
    "order_type": 0,
    "pay_type": 0,
    "pay_online_type": 0,
    "client": {
        "phone": "+36303857256",
        "email": "asdghfasjasd.hu",
        "ln": "Laci",
        "fn": "Farkas"
    },
    "order": [
        {
            "id": "1002217",
            "qnt": 5000,
            "type": "d",
            "items": []
        },
        {
            "id": "1001552",
            "qnt": 1000,
            "type": "d",
            "items": []
        }
    ]
}';
      curl_setopt($ch, CURLOPT_URL, $Url);
      curl_setopt($ch, CURLOPT_POST, 1);
      curl_setopt($ch, CURLOPT_POSTFIELDS, $Atad);
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
      curl_setopt($ch, CURLOPT_TIMEOUT, 600);
       curl_setopt($ch, CURLOPT_USERAGENT, "restaurant_name-bot");
       curl_setopt($ch, CURLOPT_REFERER, 'https://www.trattoriadisophia.hu/');
           
        
        curl_setopt($ch, CURLOPT_USERPWD, RKEEP_LOGIN.":".RKEEP_PASS);  

        curl_setopt($ch, CURLOPT_RETURNTRANSFER, True);
        

        $result = curl_exec($ch);

**Comment by avatarf** [comment]
@handras78 

Kivettem az IP-t a firewall-ból.
A logok alapján a mai első próbálkozásod még referer és user-bot nélkül jött, amivel be is kerültél a block listbe, de az utánalévők (annak ellenére hogy az első miatt blokkolva voltak) jónak tűnnek!

```
79.** - - [22/Jul/2021:07:52:25 +0200] "POST /wp-json/vendor/v1/postorder/435280001 HTTP/1.0" 503 18815 "-" "-"
79.** - - [22/Jul/2021:07:52:53 +0200] "POST /wp-json/vendor/v1/postorder/435280001 HTTP/1.0" 503 18632 "https://www.trattoriadisophia.hu/" "restaurant_name-bot"
79.** - - [22/Jul/2021:07:53:27 +0200] "POST /wp-json/vendor/v1/postorder/435280001 HTTP/1.0" 503 18632 "https://www.trattoriadisophia.hu/" "restaurant_name-bot"
79.** - - [22/Jul/2021:07:53:55 +0200] "POST /wp-json/vendor/v1/postorder/435280001 HTTP/1.0" 503 18632 "https://www.trattoriadisophia.hu/" "restaurant_name-bot"
79.** - - [22/Jul/2021:07:56:53 +0200] "POST /wp-json/vendor/v1/postorder/435280001 HTTP/1.0" 503 18632 "https://www.trattoriadisophia.hu/" "restaurant_name-bot"
79.** - - [22/Jul/2021:07:57:41 +0200] "POST /wp-json/vendor/v1/postorder/435280001 HTTP/1.0" 503 18632 "https://www.trattoriadisophia.hu/" "restaurant_name-bot"
```

**Comment by handras78** [comment]
Köszönöm, ezen túljutottam. A hitelesítéssel van még problémám. Ezt kapom válaszba:
"success":false,"data":"Invalid vendor id or token."

A hitelesítést így csinálom, ez basic auth:

        $Auth=base64_encode(RKEEP_LOGIN.":".RKEEP_PASS);
        $headers = array(
'Content-Type:application/json',        
    'Authorization: Basic '.$Auth);
    
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

Így is próbáltam, de ez se jó:
curl_setopt($ch, CURLOPT_USERPWD, (RKEEP_LOGIN.":".RKEEP_PASS));

vendor_api_doc-ba Authentication alatt lévő példa se jön ki nekem. A jelszóval úgy látom kell még valamit csinálni, nem csak base64 kódolni.
A példát amit ír:  
nekem base64_encode(login:password) = 
base64_encode(409_16_475_105:813dfdrr2d597rktfefd0766b70b61) = NDA5XzE2XzQ3NV8xMDU6ODEzZGZkcnIyZDU5N3JrdGZlZmQwNzY2YjcwYjYx
A doksiba pedig ez van: 
NDA5XzE2XzQ3NV8xMDU6MGYzN2M1MTc0MGM34DNmMDyiODFlYlf1NDIkdmI5
Az eleje a loginig még stimmel, de a jelszó nem. Mit kell még csinálnunk a jelszóval?

**Comment by avatarf** [comment]
@handras78 

Ha jól látom akkor a probléma itt egy miss communication-ből fakadt. Ahogy látom @rkeeperhun a testendpoint szerveren hozta létre nektek az accountot (és vele együtt az rest_ID-t, usert és userpasst). És ha jól látom ezt nem emeltük ki az emailben 😞  
Szóval az emailben megosztott user/pass combo a testendpoint.ucs.hu -n (`"https://testendpoint.ucs.hu/wp-json/vendor/v1/postorder/".RKEEP_REST_ID`) müködik jelenleg. Egyben akkor javasolnám is hogy folytassuk a tesztelést ott addig amíg nem 100% os az integráció.

> base64_encode(409_16_475_105:813dfdrr2d597rktfefd0766b70b61) = NDA5XzE2XzQ3NV8xMDU6ODEzZGZkcnIyZDU5N3JrdGZlZmQwNzY2YjcwYjYx
> A doksiba pedig ez van:
> NDA5XzE2XzQ3NV8xMDU6MGYzN2M1MTc0MGM34DNmMDyiODFlYlf1NDIkdmI5

☝️  a doksiban random példákat, random eredménnyel használtunk. 

```
$Auth=base64_encode(RKEEP_LOGIN.":".RKEEP_PASS);
...
'Content-Type:application/json',
'Authorization: Basic '.$Auth);
```
Logikailag jónak tűnik ha megfelelő user és pass van használva.
